const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('overlay', {
  connect: (username, key) => ipcRenderer.invoke('live:connect', username, key),
  disconnect: () => ipcRenderer.invoke('live:disconnect'),
  synthesize: (text, options) => ipcRenderer.invoke('tts:synthesize', text, options),
  onChat: fn => ipcRenderer.on('live:chat', (_e, data) => fn(data)),
  onMember: fn => ipcRenderer.on('live:member', (_e, data) => fn(data)),
  onStats: fn => ipcRenderer.on('live:stats', (_e, data) => fn(data)),
  onActivity: fn => ipcRenderer.on('live:activity', (_e, data) => fn(data)),
  onStatus: fn => ipcRenderer.on('live:status', (_e, data) => fn(data)),
  onClickThroughState: fn => ipcRenderer.on('window:click-through-state', (_e, enabled) => fn(enabled)),
  onToggleMute: fn => ipcRenderer.on('tts:toggle-mute', () => fn()),
  onMusicState: fn => ipcRenderer.on('music:state', (_e, data) => fn(data)),
  onMusicNotice: fn => ipcRenderer.on('music:notice', (_e, data) => fn(data)),
  musicState: () => ipcRenderer.invoke('music:state'),
  musicPlaylistUrl: () => ipcRenderer.invoke('music:playlist-url'),
  musicPlaylistUrls: () => ipcRenderer.invoke('music:playlist-urls'),
  musicTunnel: action => ipcRenderer.invoke('music:tunnel', action),
  onMusicTunnel: fn => ipcRenderer.on('music:tunnel', (_e, data) => fn(data)),
  musicPlaylistWindow: (action, background) => ipcRenderer.invoke('music:playlist-window', action, background),
  onMusicPlaylistWindow: fn => ipcRenderer.on('music:playlist-window', (_e, open) => fn(open)),
  musicStarted: (id, position) => ipcRenderer.send('music:started', id, position),
  musicSetEnabled: enabled => ipcRenderer.send('music:set-enabled', enabled),
  musicEnded: id => ipcRenderer.send('music:ended', id),
  musicError: (id, message) => ipcRenderer.send('music:error', id, message),
  musicControl: action => ipcRenderer.send('music:control', action),
  close: () => ipcRenderer.send('window:close'),
  minimize: () => ipcRenderer.send('window:minimize'),
  clickThrough: enabled => ipcRenderer.send('window:click-through', enabled),
  alwaysOnTop: enabled => ipcRenderer.send('window:top', enabled),
  setSize: preset => ipcRenderer.send('window:size', preset)
});
